nome = input('Nome: ')
print('Nome digitado: ', nome)
print('Primeiro caractere: ', nome[0])
print('Ultimo caractere: ', nome[-1])
print('Tres primeiros caracteres: ', nome[0:3])
print('Quarto caractere: ', nome[3])
print('Todos menos o primeiro: ', nome[1:])
print('Os dois ultimos: ', nome[-2:])